### ISSUE TITLE
Plugins sorting criteria 

### ISSUE THREAD

**Issue by pieroit** [cheshire-cat-ai/plugins-backend#26]
Cat admin shows plugins from the registry in two use cases:
- list plugins (no query)
- search (query is present)

How do we sort them?

**Comment by EugenioPetulla** [comment]
Added basic sorting for the plugins list (newest, popular) with this commit: 017a7c8

No sorting for the search (SERP) ATM and no specific algo for default sort (oldest to newest is still the default).

We have to decide if we want this in this moment or if we want to still experiment a little bit on this topic before taking a final commitment.

**Comment by pieroit** [comment]
We can take into account 3 factors:
- `p`: plugin popularity. Scaled between 0 and 1 (by ranking)
- `r`: plugin recency. Scaled between 0 and 1 (by ranking)
- `c`: plugin.json completeness. Scaled between 0 and 1 (by fraction of fields completed)

As a first form, we can just assign weight 1 to each factor and have `score = p * r * c`.
In the future we can assign weights to give more importance to some of them over others!

**Comment by pieroit** [comment]
Sorting criteria:
https://github.com/cheshire-cat-ai/plugins-backend/issues/26

**Comment by pieroit** [comment]
Sorting criteria
https://github.com/cheshire-cat-ai/plugins-backend?tab=readme-ov-file#list-all-plugins-paginated

**Comment by valentimarco** [comment]
Is this completed?

**Comment by pieroit** [comment]
Plugin sorting not a priority, since lots of people wanted to put ideas into this but nobody actually did anything

Let's wait to have a real need for this, random is good for now

**Comment by valentimarco** [comment]
The idea was write after a discussion with you and eugenio and we even wrote a solution:

> We can take into account 3 factors:
> 
>     * `p`: plugin popularity. Scaled between 0 and 1 (by ranking)
> 
>     * `r`: plugin recency. Scaled between 0 and 1 (by ranking)
> 
>     * `c`: plugin.json completeness. Scaled between 0 and 1 (by fraction of fields completed)
> 
> 
> As a first form, we can just assign weight 1 to each factor and have `score = p * r * c`. In the future we can assign weights to give more importance to some of them over others!

I asked bc this repo is a bit old in terms of feature and what to do, nothing else...
